### ISSUE TITLE
migrate to python 3.*

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eppye-bots/bots#253]
```
Support for python > 3.3
No support for both python 2.* and python 3.* 

Libraries are critical;
- django: supports python 3 (since version 1.6)
- cherrypy: supports python 3
- genshi: supports python 3
- paramiko 20130909: no
- python MySQL-db: 20130909: no
- psycopg2 (for postgreSQL): supports python 3


```

Original issue reported on code.google.com by `hjebb...@gmail.com` on 9 Sep 2013 at 4:10

**Comment by techieroshan** [comment]
Any ETA on Python 3+ compatible version especially with postgres?

**Comment by pepr** [comment]
Hi,

I have the experience with Python, and also some experience with conversion from 2 to 3, with refactoring, and the related taks. I am going to use bots in near future, and I am willing to participate with the transition.

My experience is that it would be much easier to keep the Python 2 version in maintenance mode and create the Python 3 version -- separated from Python 2 version. I believe it is easier than trying to keep it Python-version independent.

Is this issue thread the mean for coordinating the effort? Or is there any other preferred communication channel to discuss the development?

Thanks,
   Petr
