### ISSUE TITLE
mapping is the centre of bots

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eppye-bots/bots#360]
```
bigger issue/change; includes issues/changes: 356, 355, 328.
do 'as much as possible' from mapping (mapping as centre of bots)

incoming:
- access to frommail, tomail
- access to whole envelope
- one (simple) function to get incomign RAW file
outgoing:
- set envelope values
- set frommail, tomail 
- set outgoing channel
```

Original issue reported on code.google.com by `hjebb...@gmail.com` on 16 May 2015 at 2:24

**Comment by cncook001** [comment]
BOTS should be able to take an input file, do a transform/mapping (but not change anything), and return exactly the same file.

**Comment by djfurman** [comment]
> BOTS should be able to take an input file, do a transform/mapping (but not change anything), and return exactly the same file.

@cncook001, BOTS currently has this functionality.

To accomplish this:

1. Create a mapping scripting in the appropriate file type (e.g., EDIFACT `usersys/mappings/edifact`)
2. Create a translation rule to map incoming EDI type to outgoing EDI type (both the same) using this script
3. Establish the channels
4. Establish the route
5. Place the files in the infile
6. Run `bots-engine.py`

```python
# inside 'usersys/mappings/edifact/map_without_changes.py'

import bots.transform as transform

def main(inn, out):

    transform.inn2out(inn,out)

```

I use this function regularly combined with the where/change functionality to obfuscate transaction information for client presentations.

Reference: 
 https://github.com/eppye-bots/bots/blob/wiki/MappingFunction.md
