### ISSUE TITLE
-

### ISSUE THREAD

**Issue by djmicrofusion** [eppye-bots/bots#368]
The Help article for installing grammar does not give any indication of what its looking for.
I am trying to install you per-designed zip files on your site and I cant figure out why I am supposed to do to install these. Your help article lacks direction.

I am Using Python on Windows for anyone who can give Guidance it is greatly appreciated.

**Comment by djfurman** [comment]
Hi @djmicrofusion.

To install the grammars. you'll want to drop them in the bots install folder C:\Python27\... (sorry, I'm not a Windows user, on linux/mac it's /usr/local/lib/python2.7/dist-packages/bots/usersys/grammars) under whichever grammar type you're looking to use.

For example, if you're looking at the EDIFACT grammers, they would be in the usersys/grammars/edifact directory. Usersys is where all of the code you'll write in bots lands.

Checkout the 'wiki' branch of the repo and look for 'SideBarNavigation.md' for a full browser guide.
