### ISSUE TITLE
Mark version 3.2 in the commit history

### ISSUE THREAD

**Issue by djfurman** [eppye-bots/bots#377]
While still available from source forge, it would be good, especially for writing patches, to have a denotation of where the release for version 3.2 is and where the work in progress is to the other milestones tagged in issues/comments.

**Comment by lw-schick** [comment]
totally agree!

**Comment by JCapriotti** [comment]
FWIW, my coworker traced it to 672604aae0aedff02c19422030072416fff21641.

We've been using that as our internal GitLab fork.

I just noticed this thread so thought the info might be useful if the bots-edi fork takes off.
