### ISSUE TITLE
botslib runscriptyield : 'txt' is not defined

### ISSUE THREAD

**Issue by luckylud** [eppye-bots/bots#382]
In the master branch, there is a omission in botslib.py:576
If a main() communication channel script not return an iterator, the error below will appear:
DEBUG    engine : Error in process: NameError: global name 'txt' is not defined

I often use pyflakes to check my python code, it's very very useful.

I've a fix, coming from bots 3.2

**Comment by luckylud** [comment]
diff --git a/bots/botslib.py b/bots/botslib.py
index 2ea405c..ced8bcb 100644
--- a/bots/botslib.py
+++ b/bots/botslib.py
@@ -573,6 +573,7 @@ def runscriptyield(module,modulefile,functioninscript,**argv):
         for result in functiontorun(**argv):
             yield result
     except:
+        txt = txtexc()
         _exception = ScriptError(_('Script file "%(modulefile)s": "%(txt)s".'),{'modulefile':modulefile,'txt':txt})
         _exception.__cause__ = None
         raise _exception

**Comment by luckylud** [comment]
Arf ... diff display is ugly ..
No patch or diff file could be send here ...
it's so clean to work with git branch and merge a branch_fix pulled by someone.

**Comment by eppye-bots** [comment]
yes, saw that.
thanks.
henk-jan
