### ISSUE TITLE
Small Syntax Error in jobqueueserver throws error during install

### ISSUE THREAD

**Issue by mightypanders** [eppye-bots/bots#389]
https://github.com/eppye-bots/bots/blob/3277cc10b8a91c8a3dc0722d95dd1c4da8e7696a/bots/jobqueueserver.py#L70

I don't know what was intended here, but this incomplete call is an error. 
If this can just simply be removed this would be a very simple fix.

**Comment by eppye-bots** [comment]
please use official released versions.

kind regards, Henk-Jan Ebbers
